### ISSUE TITLE
Start the reviewing process 🥸

### ISSUE THREAD

**Issue by minhnimble** [Shayokh144/SurveyApp#1]
Hello Abu 👋 , it is a pleasure to meet you through this code review session and thank you for your effort on the code submission. My name is Mikey, I am currently acting as an Engineer Lead from Nimble and I am happy to be the reviewer for our code review session.

During the review process, I would like to know more about your decisions and thus I will create issues where I think there could be more improvements regarding your performance here.

At the same time, please keep in mind that this is a bi-directional process and I would love to hear back from you as well. Therefore, don’t hesitate to raise your questions/concerns and share your opinions about the implementation (if any) during the process.

If we’re aligned on any issue here and you’d like to correct them, please address the issue using proper git flow (creating a new branch, opening a Pull Request (PR) per issue and merging the code when you are ready) and I will follow up on those fixes. 😇

In the end, I really do hope that you find the process enjoyable. Good luck and happy coding 🤘

**Comment by Shayokh144** [comment]
Hello Mikey, thank you very much for starting the code review. I will go through all the issues. I would like to fix the bugs first then go for the improvements. I will let you know if I have any questions.

**Comment by minhnimble** [comment]
Hi, Abu 👋

I completed the 1st round of review just now. Please go ahead and let me know your thoughts on the proposed issues in the next couple of days, our Talent Acquisition team will follow up with you if you have any questions about the code review timeline. 🚀

Have a great evening!

**Comment by minhnimble** [comment]
Good afternoon, Abu 👋

I noticed that you have started to work on some of the raised issues. Just a friendly reminder that please consider to create a new pull request for each issue instead of putting everything into one pull request like now. 

At the same time, you are free to merge the code in each pull request when you think your implementation is good to go. This will help me track your changes for each issue easier and have a clearer view on which issue you have completed. Furthermore, as a reviewer, I don't have the permission to do the merging for your branches. 😓
![Screen Shot 2022-03-24 at 15 37 14](https://user-images.githubusercontent.com/70877098/159876000-3ec6c4de-a537-4fdf-ae1d-4e0d99a1fe72.png)

Thank you in advanced 🙏

**Comment by Shayokh144** [comment]
Thank you very much for reminding me. I will do accordingly.
