### ISSUE TITLE
[Improvement] Pagination support

### ISSUE THREAD

**Issue by minhnimble** [Shayokh144/SurveyApp#2]
As you can probably see, the surveys list API should be capable of providing more data than you have currently displayed. It would be nice if we could paginate those data by using some kind of user inputs (swipe to the end to load more, add load next page button, etc.). What do you think?

**Comment by Shayokh144** [comment]
I think a "swipe to reload more" behaviour can be implemented here when user swiped from the last survey, then we can append more survey.

**Comment by minhnimble** [comment]
sounds like a valid choice to me, I can't wait to see your implementation 🤗

**Comment by Shayokh144** [comment]
Thank you for feedback, there are few more bugs left to fix. After fixing those I will do this as soon as possible.

**Comment by minhnimble** [comment]
After checking your latest code changes from the merge, there are still a major issue that I would like to notify you about. Please help check it:
- When reached the last item of the last page, scrolling to load more will not stop and it will trigger to load and prompt errors forever. At this point, the user is unable to continue using the application and has to force quite the application.

https://user-images.githubusercontent.com/70877098/160048584-416950e2-a3c8-4b71-8c0b-76a24acadc4c.mp4

**Comment by Shayokh144** [comment]
I have given commit to fix this issue
