### ISSUE TITLE
[Bug] Unit tests got crashes and testing related concerns

### ISSUE THREAD

**Issue by minhnimble** [Shayokh144/SurveyApp#4]
It is quite nice to see that you've included a few unit tests for multiple layers (Manager, View, Presenter, Interceptor) in the application 👍. Unfortunately, there is a crash issue when I attempted to run them on my Simulator iPhone 11 iOS 15.4. Please help me check and fix this issue 🙏

![Screen Shot 2022-03-23 at 16 41 15](https://user-images.githubusercontent.com/70877098/159671031-f9786582-b08f-4468-8de1-bdd4c8df4b1b.png)

At the same time, I noticed that you haven't added unit tests for Survey screen's Presenter and Interceptor layer like you did for Login screen. It would be great if you can include the tests and increase the coverage for Survey screen as well 🙏

Lastly, I would like to know if you have any experiences in any other 3rd-party library for writing tests apart from the native XCTest? If yes can you tell me a little bit more on how you would write tests using those libraries?

**Comment by Shayokh144** [comment]
I have fixed the crash issue in this commit : https://github.com/Shayokh144/SurveyApp/commit/b6ce462d95ecfd8a1b4bafb37cd49e299abb7952

I will add more test in Survey module after fixing other bugs.

**Comment by Shayokh144** [comment]
I have use 3rd party library like Mockito, PowerMock in Android but not in iOS app. Please suggest me some libraries , this can be a great learning for me.

**Comment by minhnimble** [comment]
> I have use 3rd party library like Mockito, PowerMock in Android but not in iOS app. Please suggest me some libraries , this can be a great learning for me.

→ For iOS, I have you ever heard or have experience working with [Quick/Nimble](https://github.com/Quick/Nimble) before? This is a great Matcher library which many cool features that helps the writing unit tests much easier and effortless on Swift. Maybe you can try this out in the application if you think it is worth checking out 🙂

**Comment by Shayokh144** [comment]
Thank you for sharing. I have heard about Nimble before but didn't worked with it yet. I will definitely look at these.
