### ISSUE TITLE
[Bug] [UI] The splash screen of the application doesn't match with design

### ISSUE THREAD

**Issue by minhnimble** [Shayokh144/SurveyApp#5]
## Why

The application needs to show the splash screen like design.

## Acceptance Criteria
- The splash screen needs to look like the following design:

<img src="https://user-images.githubusercontent.com/70877098/159672812-8fb3e47f-51d3-46b9-8775-320e151be74f.png" width="300">

## Actual:

<img src="https://user-images.githubusercontent.com/70877098/159673033-543cccd2-3922-4063-b130-9cb055ef634f.png" width="300">

**Comment by Shayokh144** [comment]
splash screen image and over lay is added with below commits:
- https://github.com/Shayokh144/SurveyApp/commit/81b6b9a2078127c38c276a8f06c6ecaff0694082
- https://github.com/Shayokh144/SurveyApp/commit/7145a500ddf9262ec79441b6ea70e6606ab5d2a3

**Comment by minhnimble** [comment]
It fixed 👍
