### ISSUE TITLE
[Bug] [UI] The Login screen doesn't match with design

### ISSUE THREAD

**Issue by minhnimble** [Shayokh144/SurveyApp#6]
## Why

The application needs to show the login screen like design. Currently there are a few problems with the login screen:
- The status bar color should be white instead of black.
- No blur background image spotted.
- The text color of the email and password textfield is incorrectly set to black while the design is white. 
- The tint color of the textfields are in default blue. What do you think about setting it white for matching our design?

## Acceptance Criteria
- The login screen needs to look like the following design:

<img src="https://user-images.githubusercontent.com/70877098/159677042-d882b1c9-4956-4f90-96b0-96318a81d98a.png" width="300">

## Actual:

<img src="https://user-images.githubusercontent.com/70877098/159678708-8c44d547-f36b-4422-af96-031cb1f74957.png" width="300">

**Comment by Shayokh144** [comment]
New commit  ( https://github.com/Shayokh144/SurveyApp/commit/be70306c3f824d8c2648533a60b8b0687adecd41 )pushed for fixing this bug  which includes :
- status bar color fix
- blur image overlay background add
- text color fix
- tint color fix

**Comment by minhnimble** [comment]
Good morning Abu, I still had a few small issues on the Login screen that I would like to list them down as follow:

- The textfields and the Login button are not centered in the screen like the design.
- On small screen devices (iPhone 5/SE, etc.), the image overlay background view has weird leading and trailing white space.
  <img src="https://user-images.githubusercontent.com/70877098/160047649-fb4931b4-3480-46b2-9979-769719cda158.png" width="300">

Also, just a friendly reminder, please leave the issues open and I will help you verify and close them after checking everything. As of now, please help me reopen this issue, thank you 🙏

**Comment by Shayokh144** [comment]
Good noon. Thank you for addressing the issue. I am reopening the issue.

**Comment by Shayokh144** [comment]
I have given a commit to fix both these issues.
