### ISSUE TITLE
[Improvement] Survey list screen behavior concerns

### ISSUE THREAD

**Issue by minhnimble** [Shayokh144/SurveyApp#9]
There are a few concerns on the Survey list screen behaviors that I would like to hear your opinions on:
- It is unable to navigate to next/previous page when user trying to swipe horizontally on the image region. What do you think about enabling the swipe gesture for the entire screen region instead of just the text area?
- When swiping to the right, the app shows a new survey item in a sudden image hiding/showing manner at the end of the scroll gesture and this creates a weird UX experience that the user actually expects a horizontal transition when swiping left or right. What do you think about this problem?

https://user-images.githubusercontent.com/70877098/159690140-e2edf1ad-9b7e-44f0-9a6c-a483837935c0.mp4

**Comment by Shayokh144** [comment]
My opinion about the concerns:
- I think it will be better if swipe action is enabled for full image view, it will provide user more convenience.
- Yes the current transition is a problem, it should be solved

Probable solution:
- In current code, if I make the collection view size equal to full view size and set image in the collection view cell, then I think both problem will be  solved. Please let me know your opinion also.

**Comment by minhnimble** [comment]
sounds good to me on your approach 👍
